export const categories = [
  {
    id: 1,
    name: "Overview",
    path: "overview",
    svg: "grid-outline",
    solid_svg: "grid",
    sub_categories: [],
  },
  {
    id: 2,
    name: "Orders",
    path: "orders",
    svg: "bag-outline",
    solid_svg: "bag",
    count: 8344,
    sub_categories: [],
  },
  {
    id: 3,
    name: "Products",
    path: "products",
    svg: "cube-outline",
    solid_svg: "cube",
  },
  {
    id: 4,
    name: "Inventory",
    path: "inventory",
    svg: "home-outline",
    solid_svg: "home",
    sub_categories: [],
  },
  {
    id: 5,
    name: "Users",
    path: "users",
    svg: "person-outline",
    solid_svg: "person",
    sub_categories: [
      {
        id: 51,
        name: "Overview",
        path: "users/overview",
        svg: "person-outline",
        solid_svg: "person",
      },
    ],
  },
  {
    id: 6,
    name: "Analytics",
    path: "Analytics",
    svg: "analytics",
    solid_svg: "analytics",
    sub_categories: [],
  },
  {
    id: 7,
    name: "Settings",
    path: "settings",
    svg: "settings-outline",
    solid_svg: "settings",
    sub_categories: [],
  },
  {
    id: 8,
    name: "Support & Help",
    path: "supportandhelp",
    svg: "help-circle-outline",
    solid_svg: "help-circle",
    sub_categories: [],
  },
];
